name = "aoc2024"
version = "1.0.0"

licences = ["Apache-2.0"]
repository = { type = "github", user = "denaun", repo = "aoc-2024" }

[dependencies]
gleam_stdlib = ">= 0.45.0 and < 2.0.0"
atto = ">= 1.0.0 and < 2.0.0"
counter = ">= 1.0.4 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
glacier = ">= 1.1.0 and < 2.0.0"
adglent = ">= 1.3.0 and < 2.0.0"
